#!/bin/bash
set -e 
sudo docker stop $(sudo docker ps -q --filter ancestor=soloekaterina/sitik )
sudo docker rm $(sudo docker ps --all -q --filter ancestor=soloekaterina/sitik )
sudo docker build -t soloekaterina/sitik .
sudo docker run -d -p 8082:8082 soloekaterina/sitik
